#!/bin/bash

set -e

CONFIG="$HOME/.localnet/relayer/config.toml"

mkdir -p "$HOME/.localnet/relayer"

cat <<EOF > "$CONFIG"
[global]
strategy = 'packets'
filter = false
log_level = 'info'
clear_packets_interval = 100

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'sifchain-a'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'sif'
key_name = 'sifchain-a'
store_prefix = 'ibc'
max_gas = 3000000
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'sifchain-b'
rpc_addr = 'http://127.0.0.2:26657'
grpc_addr = 'http://127.0.0.2:9090'
websocket_addr = 'ws://127.0.0.2:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'sif'
key_name = 'sifchain-b'
store_prefix = 'ibc'
max_gas = 3000000
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
EOF

hermes --config "$CONFIG" \
  keys restore sifchain-a \
  --mnemonic "race draft rival universe maid cheese steel logic crowd fork comic easy truth drift tomorrow eye buddy head time cash swing swift midnight borrow"

hermes --config "$CONFIG" \
  keys restore sifchain-b  \
  --mnemonic "hand inmate canvas head lunar naive increase recycle dog ecology inhale december wide bubble hockey dice worth gravity ketchup feed balance parent secret orchard"

hermes --config "$CONFIG" create channel sifchain-a sifchain-b \
  --port-a transfer \
  --port-b transfer

hermes --config "$CONFIG" start
